title: Examples of Openbadges v3 Credentials for Edubadges
email: ber.kessels@surf.nl

baseurl: "/obv3-examples" # the subpath of your site, e.g. /blog
url: "https://www.educredentials.eu/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username: educredentials

fenced_code_blocks: true
show_dir_listing: false

defaults:
  - scope:
      path: "examples.md"
    values:
      permalink: "/"
  - scope:
      path: "offers/img"
    values:
      offer: true

collections:
  credentials:
    output: true
    layout: credential
    permalink: /credentials/:name

plugins:
  - jekyl-remote-theme
remote_theme: pages-themes/slate@v0.2.0

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - "README.md"
  - "*.sh"
  - "Makefile"
